/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export interface MarketplaceEscrowInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "admin"
      | "cancelDeal"
      | "confirmReceived"
      | "createDeal"
      | "deals"
      | "fundDeal"
      | "markShipped"
      | "nextDealId"
      | "raiseDispute"
      | "resolveDispute"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "DealCancelled"
      | "DealCompleted"
      | "DealCreated"
      | "DealDisputed"
      | "DealFunded"
      | "DealResolved"
      | "DealShipped"
  ): EventFragment;

  encodeFunctionData(functionFragment: "admin", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "cancelDeal",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "confirmReceived",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "createDeal",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "deals", values: [BigNumberish]): string;
  encodeFunctionData(
    functionFragment: "fundDeal",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "markShipped",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "nextDealId",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "raiseDispute",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "resolveDispute",
    values: [BigNumberish, boolean]
  ): string;

  decodeFunctionResult(functionFragment: "admin", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "cancelDeal", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "confirmReceived",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "createDeal", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "deals", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "fundDeal", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "markShipped",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "nextDealId", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "raiseDispute",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "resolveDispute",
    data: BytesLike
  ): Result;
}

export namespace DealCancelledEvent {
  export type InputTuple = [id: BigNumberish];
  export type OutputTuple = [id: bigint];
  export interface OutputObject {
    id: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DealCompletedEvent {
  export type InputTuple = [id: BigNumberish];
  export type OutputTuple = [id: bigint];
  export interface OutputObject {
    id: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DealCreatedEvent {
  export type InputTuple = [
    id: BigNumberish,
    seller: AddressLike,
    price: BigNumberish
  ];
  export type OutputTuple = [id: bigint, seller: string, price: bigint];
  export interface OutputObject {
    id: bigint;
    seller: string;
    price: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DealDisputedEvent {
  export type InputTuple = [id: BigNumberish];
  export type OutputTuple = [id: bigint];
  export interface OutputObject {
    id: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DealFundedEvent {
  export type InputTuple = [
    id: BigNumberish,
    buyer: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [id: bigint, buyer: string, amount: bigint];
  export interface OutputObject {
    id: bigint;
    buyer: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DealResolvedEvent {
  export type InputTuple = [id: BigNumberish, releasedToSeller: boolean];
  export type OutputTuple = [id: bigint, releasedToSeller: boolean];
  export interface OutputObject {
    id: bigint;
    releasedToSeller: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DealShippedEvent {
  export type InputTuple = [id: BigNumberish];
  export type OutputTuple = [id: bigint];
  export interface OutputObject {
    id: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface MarketplaceEscrow extends BaseContract {
  connect(runner?: ContractRunner | null): MarketplaceEscrow;
  waitForDeployment(): Promise<this>;

  interface: MarketplaceEscrowInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  admin: TypedContractMethod<[], [string], "view">;

  cancelDeal: TypedContractMethod<[_id: BigNumberish], [void], "nonpayable">;

  confirmReceived: TypedContractMethod<
    [_id: BigNumberish],
    [void],
    "nonpayable"
  >;

  createDeal: TypedContractMethod<
    [_price: BigNumberish],
    [bigint],
    "nonpayable"
  >;

  deals: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, string, string, bigint, bigint] & {
        id: bigint;
        seller: string;
        buyer: string;
        price: bigint;
        status: bigint;
      }
    ],
    "view"
  >;

  fundDeal: TypedContractMethod<[_id: BigNumberish], [void], "payable">;

  markShipped: TypedContractMethod<[_id: BigNumberish], [void], "nonpayable">;

  nextDealId: TypedContractMethod<[], [bigint], "view">;

  raiseDispute: TypedContractMethod<[_id: BigNumberish], [void], "nonpayable">;

  resolveDispute: TypedContractMethod<
    [_id: BigNumberish, _releaseToSeller: boolean],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "admin"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "cancelDeal"
  ): TypedContractMethod<[_id: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "confirmReceived"
  ): TypedContractMethod<[_id: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "createDeal"
  ): TypedContractMethod<[_price: BigNumberish], [bigint], "nonpayable">;
  getFunction(
    nameOrSignature: "deals"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, string, string, bigint, bigint] & {
        id: bigint;
        seller: string;
        buyer: string;
        price: bigint;
        status: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "fundDeal"
  ): TypedContractMethod<[_id: BigNumberish], [void], "payable">;
  getFunction(
    nameOrSignature: "markShipped"
  ): TypedContractMethod<[_id: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "nextDealId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "raiseDispute"
  ): TypedContractMethod<[_id: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "resolveDispute"
  ): TypedContractMethod<
    [_id: BigNumberish, _releaseToSeller: boolean],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "DealCancelled"
  ): TypedContractEvent<
    DealCancelledEvent.InputTuple,
    DealCancelledEvent.OutputTuple,
    DealCancelledEvent.OutputObject
  >;
  getEvent(
    key: "DealCompleted"
  ): TypedContractEvent<
    DealCompletedEvent.InputTuple,
    DealCompletedEvent.OutputTuple,
    DealCompletedEvent.OutputObject
  >;
  getEvent(
    key: "DealCreated"
  ): TypedContractEvent<
    DealCreatedEvent.InputTuple,
    DealCreatedEvent.OutputTuple,
    DealCreatedEvent.OutputObject
  >;
  getEvent(
    key: "DealDisputed"
  ): TypedContractEvent<
    DealDisputedEvent.InputTuple,
    DealDisputedEvent.OutputTuple,
    DealDisputedEvent.OutputObject
  >;
  getEvent(
    key: "DealFunded"
  ): TypedContractEvent<
    DealFundedEvent.InputTuple,
    DealFundedEvent.OutputTuple,
    DealFundedEvent.OutputObject
  >;
  getEvent(
    key: "DealResolved"
  ): TypedContractEvent<
    DealResolvedEvent.InputTuple,
    DealResolvedEvent.OutputTuple,
    DealResolvedEvent.OutputObject
  >;
  getEvent(
    key: "DealShipped"
  ): TypedContractEvent<
    DealShippedEvent.InputTuple,
    DealShippedEvent.OutputTuple,
    DealShippedEvent.OutputObject
  >;

  filters: {
    "DealCancelled(uint256)": TypedContractEvent<
      DealCancelledEvent.InputTuple,
      DealCancelledEvent.OutputTuple,
      DealCancelledEvent.OutputObject
    >;
    DealCancelled: TypedContractEvent<
      DealCancelledEvent.InputTuple,
      DealCancelledEvent.OutputTuple,
      DealCancelledEvent.OutputObject
    >;

    "DealCompleted(uint256)": TypedContractEvent<
      DealCompletedEvent.InputTuple,
      DealCompletedEvent.OutputTuple,
      DealCompletedEvent.OutputObject
    >;
    DealCompleted: TypedContractEvent<
      DealCompletedEvent.InputTuple,
      DealCompletedEvent.OutputTuple,
      DealCompletedEvent.OutputObject
    >;

    "DealCreated(uint256,address,uint256)": TypedContractEvent<
      DealCreatedEvent.InputTuple,
      DealCreatedEvent.OutputTuple,
      DealCreatedEvent.OutputObject
    >;
    DealCreated: TypedContractEvent<
      DealCreatedEvent.InputTuple,
      DealCreatedEvent.OutputTuple,
      DealCreatedEvent.OutputObject
    >;

    "DealDisputed(uint256)": TypedContractEvent<
      DealDisputedEvent.InputTuple,
      DealDisputedEvent.OutputTuple,
      DealDisputedEvent.OutputObject
    >;
    DealDisputed: TypedContractEvent<
      DealDisputedEvent.InputTuple,
      DealDisputedEvent.OutputTuple,
      DealDisputedEvent.OutputObject
    >;

    "DealFunded(uint256,address,uint256)": TypedContractEvent<
      DealFundedEvent.InputTuple,
      DealFundedEvent.OutputTuple,
      DealFundedEvent.OutputObject
    >;
    DealFunded: TypedContractEvent<
      DealFundedEvent.InputTuple,
      DealFundedEvent.OutputTuple,
      DealFundedEvent.OutputObject
    >;

    "DealResolved(uint256,bool)": TypedContractEvent<
      DealResolvedEvent.InputTuple,
      DealResolvedEvent.OutputTuple,
      DealResolvedEvent.OutputObject
    >;
    DealResolved: TypedContractEvent<
      DealResolvedEvent.InputTuple,
      DealResolvedEvent.OutputTuple,
      DealResolvedEvent.OutputObject
    >;

    "DealShipped(uint256)": TypedContractEvent<
      DealShippedEvent.InputTuple,
      DealShippedEvent.OutputTuple,
      DealShippedEvent.OutputObject
    >;
    DealShipped: TypedContractEvent<
      DealShippedEvent.InputTuple,
      DealShippedEvent.OutputTuple,
      DealShippedEvent.OutputObject
    >;
  };
}
