/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export interface SecureMarketplaceInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "admin"
      | "cancelBeforeShipped"
      | "confirmReceived"
      | "createTrade"
      | "fundTrade"
      | "markShipped"
      | "nextTradeId"
      | "openDispute"
      | "resolveDispute"
      | "trades"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "TradeCancelled"
      | "TradeCompleted"
      | "TradeCreated"
      | "TradeDisputed"
      | "TradeFunded"
      | "TradeResolved"
      | "TradeShipped"
  ): EventFragment;

  encodeFunctionData(functionFragment: "admin", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "cancelBeforeShipped",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "confirmReceived",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "createTrade",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "fundTrade",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "markShipped",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "nextTradeId",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "openDispute",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "resolveDispute",
    values: [BigNumberish, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "trades",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(functionFragment: "admin", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "cancelBeforeShipped",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "confirmReceived",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createTrade",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "fundTrade", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "markShipped",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "nextTradeId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "openDispute",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "resolveDispute",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "trades", data: BytesLike): Result;
}

export namespace TradeCancelledEvent {
  export type InputTuple = [tradeId: BigNumberish];
  export type OutputTuple = [tradeId: bigint];
  export interface OutputObject {
    tradeId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TradeCompletedEvent {
  export type InputTuple = [tradeId: BigNumberish];
  export type OutputTuple = [tradeId: bigint];
  export interface OutputObject {
    tradeId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TradeCreatedEvent {
  export type InputTuple = [
    tradeId: BigNumberish,
    seller: AddressLike,
    price: BigNumberish
  ];
  export type OutputTuple = [tradeId: bigint, seller: string, price: bigint];
  export interface OutputObject {
    tradeId: bigint;
    seller: string;
    price: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TradeDisputedEvent {
  export type InputTuple = [tradeId: BigNumberish];
  export type OutputTuple = [tradeId: bigint];
  export interface OutputObject {
    tradeId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TradeFundedEvent {
  export type InputTuple = [
    tradeId: BigNumberish,
    buyer: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [tradeId: bigint, buyer: string, amount: bigint];
  export interface OutputObject {
    tradeId: bigint;
    buyer: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TradeResolvedEvent {
  export type InputTuple = [tradeId: BigNumberish, refundedBuyer: boolean];
  export type OutputTuple = [tradeId: bigint, refundedBuyer: boolean];
  export interface OutputObject {
    tradeId: bigint;
    refundedBuyer: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TradeShippedEvent {
  export type InputTuple = [tradeId: BigNumberish];
  export type OutputTuple = [tradeId: bigint];
  export interface OutputObject {
    tradeId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface SecureMarketplace extends BaseContract {
  connect(runner?: ContractRunner | null): SecureMarketplace;
  waitForDeployment(): Promise<this>;

  interface: SecureMarketplaceInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  admin: TypedContractMethod<[], [string], "view">;

  cancelBeforeShipped: TypedContractMethod<
    [tradeId: BigNumberish],
    [void],
    "nonpayable"
  >;

  confirmReceived: TypedContractMethod<
    [tradeId: BigNumberish],
    [void],
    "nonpayable"
  >;

  createTrade: TypedContractMethod<
    [price: BigNumberish],
    [bigint],
    "nonpayable"
  >;

  fundTrade: TypedContractMethod<[tradeId: BigNumberish], [void], "payable">;

  markShipped: TypedContractMethod<
    [tradeId: BigNumberish],
    [void],
    "nonpayable"
  >;

  nextTradeId: TypedContractMethod<[], [bigint], "view">;

  openDispute: TypedContractMethod<
    [tradeId: BigNumberish],
    [void],
    "nonpayable"
  >;

  resolveDispute: TypedContractMethod<
    [tradeId: BigNumberish, refundBuyer: boolean],
    [void],
    "nonpayable"
  >;

  trades: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, string, bigint, bigint] & {
        seller: string;
        buyer: string;
        price: bigint;
        status: bigint;
      }
    ],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "admin"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "cancelBeforeShipped"
  ): TypedContractMethod<[tradeId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "confirmReceived"
  ): TypedContractMethod<[tradeId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "createTrade"
  ): TypedContractMethod<[price: BigNumberish], [bigint], "nonpayable">;
  getFunction(
    nameOrSignature: "fundTrade"
  ): TypedContractMethod<[tradeId: BigNumberish], [void], "payable">;
  getFunction(
    nameOrSignature: "markShipped"
  ): TypedContractMethod<[tradeId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "nextTradeId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "openDispute"
  ): TypedContractMethod<[tradeId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "resolveDispute"
  ): TypedContractMethod<
    [tradeId: BigNumberish, refundBuyer: boolean],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "trades"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, string, bigint, bigint] & {
        seller: string;
        buyer: string;
        price: bigint;
        status: bigint;
      }
    ],
    "view"
  >;

  getEvent(
    key: "TradeCancelled"
  ): TypedContractEvent<
    TradeCancelledEvent.InputTuple,
    TradeCancelledEvent.OutputTuple,
    TradeCancelledEvent.OutputObject
  >;
  getEvent(
    key: "TradeCompleted"
  ): TypedContractEvent<
    TradeCompletedEvent.InputTuple,
    TradeCompletedEvent.OutputTuple,
    TradeCompletedEvent.OutputObject
  >;
  getEvent(
    key: "TradeCreated"
  ): TypedContractEvent<
    TradeCreatedEvent.InputTuple,
    TradeCreatedEvent.OutputTuple,
    TradeCreatedEvent.OutputObject
  >;
  getEvent(
    key: "TradeDisputed"
  ): TypedContractEvent<
    TradeDisputedEvent.InputTuple,
    TradeDisputedEvent.OutputTuple,
    TradeDisputedEvent.OutputObject
  >;
  getEvent(
    key: "TradeFunded"
  ): TypedContractEvent<
    TradeFundedEvent.InputTuple,
    TradeFundedEvent.OutputTuple,
    TradeFundedEvent.OutputObject
  >;
  getEvent(
    key: "TradeResolved"
  ): TypedContractEvent<
    TradeResolvedEvent.InputTuple,
    TradeResolvedEvent.OutputTuple,
    TradeResolvedEvent.OutputObject
  >;
  getEvent(
    key: "TradeShipped"
  ): TypedContractEvent<
    TradeShippedEvent.InputTuple,
    TradeShippedEvent.OutputTuple,
    TradeShippedEvent.OutputObject
  >;

  filters: {
    "TradeCancelled(uint256)": TypedContractEvent<
      TradeCancelledEvent.InputTuple,
      TradeCancelledEvent.OutputTuple,
      TradeCancelledEvent.OutputObject
    >;
    TradeCancelled: TypedContractEvent<
      TradeCancelledEvent.InputTuple,
      TradeCancelledEvent.OutputTuple,
      TradeCancelledEvent.OutputObject
    >;

    "TradeCompleted(uint256)": TypedContractEvent<
      TradeCompletedEvent.InputTuple,
      TradeCompletedEvent.OutputTuple,
      TradeCompletedEvent.OutputObject
    >;
    TradeCompleted: TypedContractEvent<
      TradeCompletedEvent.InputTuple,
      TradeCompletedEvent.OutputTuple,
      TradeCompletedEvent.OutputObject
    >;

    "TradeCreated(uint256,address,uint256)": TypedContractEvent<
      TradeCreatedEvent.InputTuple,
      TradeCreatedEvent.OutputTuple,
      TradeCreatedEvent.OutputObject
    >;
    TradeCreated: TypedContractEvent<
      TradeCreatedEvent.InputTuple,
      TradeCreatedEvent.OutputTuple,
      TradeCreatedEvent.OutputObject
    >;

    "TradeDisputed(uint256)": TypedContractEvent<
      TradeDisputedEvent.InputTuple,
      TradeDisputedEvent.OutputTuple,
      TradeDisputedEvent.OutputObject
    >;
    TradeDisputed: TypedContractEvent<
      TradeDisputedEvent.InputTuple,
      TradeDisputedEvent.OutputTuple,
      TradeDisputedEvent.OutputObject
    >;

    "TradeFunded(uint256,address,uint256)": TypedContractEvent<
      TradeFundedEvent.InputTuple,
      TradeFundedEvent.OutputTuple,
      TradeFundedEvent.OutputObject
    >;
    TradeFunded: TypedContractEvent<
      TradeFundedEvent.InputTuple,
      TradeFundedEvent.OutputTuple,
      TradeFundedEvent.OutputObject
    >;

    "TradeResolved(uint256,bool)": TypedContractEvent<
      TradeResolvedEvent.InputTuple,
      TradeResolvedEvent.OutputTuple,
      TradeResolvedEvent.OutputObject
    >;
    TradeResolved: TypedContractEvent<
      TradeResolvedEvent.InputTuple,
      TradeResolvedEvent.OutputTuple,
      TradeResolvedEvent.OutputObject
    >;

    "TradeShipped(uint256)": TypedContractEvent<
      TradeShippedEvent.InputTuple,
      TradeShippedEvent.OutputTuple,
      TradeShippedEvent.OutputObject
    >;
    TradeShipped: TypedContractEvent<
      TradeShippedEvent.InputTuple,
      TradeShippedEvent.OutputTuple,
      TradeShippedEvent.OutputObject
    >;
  };
}
